### ISSUE TITLE
Feature request: support logging into IMAP

### ISSUE THREAD

**Issue by djhaskin987** [mricon/b4#32]
It would be really handy if b4 could retrieve a thread of with a particular message ID from my inbox using IMAP for one-off commits when I'm away from my mutt set-up, and also to help spread git email to the masses. That way, anywone with b4 on their laptops could accept patches, regardless of what mail set-up they use.

**Comment by mricon** [comment]
Unfortunately, IMAP configuration greatly depends on the server implementation (Courier, Dovecot, GMail), so it's not simple to implement and even less simple to correctly configure. For this reason, I recommend using either isync or lei to accomplish what you're looking for instead of putting this functionality directly into b4.
